# Generated by Django 5.1.2 on 2024-10-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_rename_id_products__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='_id',
        ),
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
