# Generated by Django 5.1.2 on 2024-10-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_remove_products__id_products_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='num_reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
